-- Initial schema for Supply Chain Visualizer.
-- Matches the JPA entity model (validated at boot via spring.jpa.hibernate.ddl-auto=validate).
-- Identity columns auto-create sequences named <table>_id_seq, which V2 seed data relies on.

CREATE TABLE nodes (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(255) NOT NULL,
    type       varchar(255) NOT NULL,
    latitude   double precision NOT NULL,
    longitude  double precision NOT NULL,
    capacity   integer,
    status     varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);

CREATE TABLE products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL,
    description varchar(255),
    unit_price  double precision NOT NULL,
    weight      double precision,
    sku         varchar(255),
    status      varchar(255) NOT NULL,
    created_at  timestamp(6) NOT NULL,
    updated_at  timestamp(6)
);

CREATE TABLE connections (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id           bigint NOT NULL REFERENCES nodes (id),
    target_id           bigint NOT NULL REFERENCES nodes (id),
    transportation_type varchar(255),
    distance            double precision,
    travel_time         integer,
    cost_per_unit       double precision,
    status              varchar(255) NOT NULL,
    created_at          timestamp(6) NOT NULL,
    updated_at          timestamp(6)
);

CREATE TABLE inventory (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id       bigint NOT NULL REFERENCES nodes (id),
    product_id    bigint NOT NULL REFERENCES products (id),
    quantity      integer NOT NULL,
    min_threshold integer,
    max_threshold integer,
    created_at    timestamp(6) NOT NULL,
    updated_at    timestamp(6)
);

CREATE TABLE shipments (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id         bigint NOT NULL REFERENCES nodes (id),
    destination_id    bigint NOT NULL REFERENCES nodes (id),
    status            varchar(255) NOT NULL,
    departure_date    date,
    estimated_arrival date,
    actual_arrival    date,
    created_at        timestamp(6) NOT NULL,
    updated_at        timestamp(6)
);

CREATE TABLE shipment_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id bigint REFERENCES shipments (id),
    product_id  bigint NOT NULL REFERENCES products (id),
    quantity    integer NOT NULL
);

CREATE TABLE users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   varchar(255) NOT NULL UNIQUE,
    email      varchar(255) UNIQUE,
    password   varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6)
);

CREATE TABLE user_roles (
    user_id bigint NOT NULL REFERENCES users (id),
    role    varchar(255)
);
